function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
	elseif message_id == hash("proxy_unloaded") then
		print("Scene unloaded")
	end
end

function on_input(self, action_id, action)	
	if action_id == hash("interact") or action_id == hash("photo") then
		print(msg.post("main:/scene_controller", "change_scene", { proxy = "surface_proxy" }))
	end
end